### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'T'

### ISSUE THREAD

**Issue by Jayzhaowj** [aicherc/sgmcmc_ssm_code#1]
Hello Christopher,

I have encountered issues when I try to run demo/synthetic/lgssm_demo.py. 
Traceback (most recent call last):
  File "demo/synthetic/lgssm_demo.py", line 94, in <module>
    sampler.sample_gibbs()
  File "/Users/jay/Documents/research/sgmcmc_ssm_code/sgmcmc_ssm/models/lgssm/sampler.py", line 93, in sample_gibbs
    prior=self.prior,
  File "/Users/jay/Documents/research/sgmcmc_ssm_code/sgmcmc_ssm/sgmcmc_sampler.py", line 1680, in parameters_gibbs_sample
    observations, latent_vars, **kwargs,
  File "/Users/jay/Documents/research/sgmcmc_ssm_code/sgmcmc_ssm/models/lgssm/helper.py", line 520, in calc_gibbs_sufficient_statistic
    Sx_prevprev = PsiT_prev.T.dot(PsiT_prev)
AttributeError: 'tuple' object has no attribute 'T'

My python version is 3.7.3. Could you please help me look at it? Thank you very much.

Best,
Wenjie

**Comment by aicherc** [comment]
Hi Wenjie,

Thanks for catching this. 
Last month I made some changes to the internal organization of the internal helper classes, but did not fully test all the demos.
I believe commit `eae22cf` should fix this issue (along with a few others that occur for the synthetic demo examples).

Let me know if the issue persists.

Thanks again,
Chris

**Comment by Jayzhaowj** [comment]
Hello Chris,

Thank you for quick response, I think now it works.

Best,
Wenjie

**Comment by Jayzhaowj** [comment]
Hello Chris,

Thank you for your quick response. I think now it works.

Best,
Wenjie
